name = "AppleSkin"
filename = "appleskin-forge-mc1.16.x-2.2.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3512/372/appleskin-forge-mc1.16.x-2.2.0.jar"
hash-format = "murmur2"
hash = "3380059684"

[update]
[update.curseforge]
file-id = 3512372
project-id = 248787
release-channel = "beta"
