name = "Caves & Cliffs Backport"
filename = "cavesandcliffs-1.16.5-7.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3592/876/cavesandcliffs-1.16.5-7.2.0.jar"
hash-format = "murmur2"
hash = "1750592001"

[update]
[update.curseforge]
file-id = 3592876
project-id = 417430
release-channel = "beta"
