name = "Just Enough Items (JEI)"
filename = "jei-1.16.5-7.7.1.139.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/83/jei-1.16.5-7.7.1.139.jar"
hash-format = "murmur2"
hash = "2460059369"

[update]
[update.curseforge]
file-id = 3590083
project-id = 238222
release-channel = "beta"
