name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.19-build.258.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3584/819/kubejs-forge-1605.3.19-build.258.jar"
hash-format = "murmur2"
hash = "2160390070"

[update]
[update.curseforge]
file-id = 3584819
project-id = 238086
release-channel = "beta"
